### ISSUE TITLE
error in the auto-completion of URLs

### ISSUE THREAD

**Issue by Ondastm** [displane/balena-displane#2]
Hello, there is an error in the auto-completion of URLs.
When I enter an address https://www.123.com everything is fine.
If I enter e.g. "https://uhr.ptb.de/", "https://uhr.ptb.de/uhr.ptb.de/" appears automatically. The domain is repeated. I'm not sure what format or string triggers this.

**Comment by megalan247** [comment]
Hi there, thanks for the report!
This should now be fixed. And instead of auto formatting the URL, I put a small hint in the placeholder of the URL. Thanks!
